# Generated by Django 5.0.6 on 2024-07-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_remove_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
    ]
